Repository approvers/site, pull requests merged in 2021-07, with the labels that each got.

#183 ステージングの反映とステージング環境のテスト
  .eslintrc
  .github/CODEOWNERS
  .husky/.gitignore
  .husky/pre-commit
  package.json
  src/components/footer.tsx
  src/components/header.tsx
  src/components/layout.tsx
  src/components/navigation.tsx
  src/scss/_color.variable.scss
  src/scss/components/external-link.module.scss
  src/scss/components/header.module.scss
  src/scss/components/layout.module.scss
  src/scss/components/navigation.module.scss
  src/scss/global.scss
  src/scss/pages/blog/markdown.module.scss
  yarn.lock
Labels: enhancement

#211 メンバーリストのスタイルの修正
  src/scss/_details.variable.scss
  src/scss/components/avatar.module.scss
  src/scss/components/paper.module.scss
  src/scss/pages/blog.module.scss
  src/scss/pages/member.module.scss
Labels: bug

#212 代替画像処理の修正
  package.json
  src/components/avatar.tsx
  yarn.lock
Labels: bug, dependencies

#215 簡単なリファクタ
  src/lib/blog-fetch.ts
  src/lib/gtag.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/blog.tsx
Labels: refactor

#218 HTTP 404のページを追加
  src/pages/404.tsx
  src/scss/pages/404.module.scss
Labels: enhancement
